version: '3'
services:
  pgsql:
    image: postgres:9.6.17
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=webfleet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webfleet
    volumes:
      - ./pgsql:/var/lib/postgresql/data
  mocker:
    image: mockserver/mockserver
    ports:
    - 9999:1080
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/mocked-replies.json
    volumes:
      - ../src/it/resources:/config
  rabbitmq:
    image: rabbitmq:3.8.5-management
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672